update resolver parameters (#526)
* resolver: fix default accepted_payload_size

This fixes the error:
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Comparison of: Undef Value < Integer, is not possible. Caused by 'Only Strings, Numbers, Timespans, Timestamps, and Versions are comparable'. (file: /etc/puppetlabs/code/modules/haproxy/manifests/resolver.pp, line: 125, column: 30)

HAProxy allows this parameter to be unset, and the code here works with
this ok, aside from the bounds check. Replace the bounds check with a
parameter type declaration, so that puppet itself will do the check for
us.

Update tests accordingly.

* resolver: support parse-resolv-conf parameter

The parse-resolv-conf parameter can be used on its own or in conjunction
with the nameservers parameter.

Adjust the nameservers parameter default to allow the template to work;
an empty hash results in no nameservers specified.

Add a new test.

* resolver: visually re-align parameter assignments